name: radio_player
description: A Flutter plugin to play streaming audio content with background support and lock screen controls.
version: 1.5.1
homepage: https://github.com/cheebeez/radio_player

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cheebeez.radio_player
        pluginClass: RadioPlayerPlugin
      ios:
        pluginClass: RadioPlayerPlugin
